import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/layout/Sidebar";
import TopbarWrapper from "./components/layout/TopbarWrapper";
import "../globals.css";
import { SidebarProvider } from "./context/SidebarContext";


export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WikiLet",
  description: "Generated by create next app",
};

export default function HostLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body>
        <SidebarProvider>
          <div className="flex flex-col h-screen">
            <TopbarWrapper />
            <div className="flex grow overflow-hidden">
              <Sidebar />
              <main className="bg-[#F8F9FA] px-4 py-8 sm:px-8 sm:py-12 grow overflow-y-auto">
                {children}
              </main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
 