import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./components/layout/Sidebar";
import TopbarWrapper from "./components/layout/TopbarWrapper";
import "../globals.css";


export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WikiLet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body>
        <div className="flex flex-col h-screen">
          <TopbarWrapper />
          <div className="flex grow">
            <Sidebar />
            <main className="bg-[#F8F9FA] p-4 sm:px-8 sm:py-12 grow">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
