import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavbarWrapper from "../../components/layout/NavbarWrapper";
import PopupScreen from "../../components/layout/PopupScreen";


export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WikiLet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body>
        <PopupScreen />
        <NavbarWrapper />
        {children}
      </body>
    </html>
  );
}
