import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./agent/components/layout/Sidebar";
import TopbarWrapper from "./agent/components/layout/TopbarWrapper";
import "../globals.css";


export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "WikiLet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body>
        <div className="flex flex-col h-screen">
          <TopbarWrapper />
          <div className="flex grow">
            <Sidebar />
            <div className="h-screen p-4">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
